/** @format */

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/Card";
//import CoffeeStoresData from "../data/coffee-stores.json";
import { fetchCooffeStores } from "../lib/coffee-stores";

import UserTrackLocation from "../hooks/user-track-locations.js";

export async function getStaticProps(context) {
	const CoffeeStores = await fetchCooffeStores();

	return {
		props: {
			CoffeeStores,
		},
	};
}

export default function Home(props) {
	const { LatLong, handleTrackLocation, locationErrMsg, isFindingLocation } = UserTrackLocation();
	const handleOnBannerBtnClick = () => {
		handleTrackLocation();
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee Lovers</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<Banner buttonText={isFindingLocation ? "Locating..." : "View Stores Nearby"} handleOnClick={handleOnBannerBtnClick} />
				{locationErrMsg && <p>Something Went Wrong:{locationErrMsg}</p>}
				<div className={styles.heroImage}>
					<Image src='/static/hero-banner.png' alt='banner' width={700} height={300} />
				</div>
				{props.CoffeeStores.length > 0 && (
					<div className={styles.sectionWrapper}>
						<h2 className={styles.headingtwo}>Chandkheda Stores</h2>
						<div className={styles.cardLayout}>
							{props.CoffeeStores.map((CoffeeStore) => {
								return (
									<Card
										key={CoffeeStore.id}
										className={styles.card}
										name={CoffeeStore.name}
										imgUrl={
											CoffeeStore.imgUrl ||
											"https://images.unsplash.com/photo-1498804103079-a6351b050096?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2468&q=80"
										}
										href={`/coffee-store/${CoffeeStore.id}`}
									/>
								);
							})}
						</div>
					</div>
				)}
			</main>
		</div>
	);
}
